apiVersion: v1
kind: Pod
metadata:
  name: symfony-api
spec:
  containers:
  - image: symfonypower/php7-symfony:1.0.0
    ports:
    - containerPort: 9000
    name: sowboy-api-code
    volumeMounts:
    - mountPath: /var/www
      name: booking-api-code
  volumes:
  - name: booking-api-code
    hostPath:
      # directory location on host
      path: ./
      
 - image: symfonypower/apache:1.0.0
   ports:
   - containerPort: 80
    name: sowboy-booking-api
    volumeMounts:
    - mountPath: /var/www/html
      name: booking-api
  volumes:
  - name: booking-api
    hostPath:
      # directory location on host
      path: ./
      
 - image: mysql:8.0
   name: mysql
   imagePullPolicy: Never
   env:
   - name: MYSQL_ROOT_PASSWORD
     value: passroot
   - name: MYSQL_DATABASE
     value: serBooking
   - name: MYSQL_USER
     value: db_user
   - name: MYSQL_PASSWORD
     value: passroot
   args: ["--default-authentication-plugin=mysql_native_password"]
   ports:
   - containerPort: 3306
