apiVersion: v1
kind: Pod
metadata:
  name: symfony-api
spec:
  containers:
  - image: symfonypower/php7-symfony:1.0.0
    ports:
    - containerPort: 9000
    name: sowboy-api-code
    volumeMounts:
    - mountPath: /var/www
      name: booking-api-code
  volumes:
  - name: booking-api-code
    hostPath:
      # directory location on host
      path: ./
      
  - image: symfonypower/apache:1.0.0
    ports:
    - containerPort: 80
    name: sowboy-booking-api
    volumeMounts:
    - mountPath: /var/www/html
      name: booking-api
  volumes:
  - name: booking-api
    hostPath:
      # directory location on host
      path: ./
      
  - image: mysql:5.6
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: passroot
    - name: MYSQL_DATABASE
      value: serBooking
    ports:
    - containerPort: 3306
   
