apiVersion: v1
kind: Deployment
metadata:
  name: symfony-api
spec:
  volumes:
    - name: api-pv-storage
      persistentVolumeClaim:
       claimName: api-pv-claim
  containers:
  - image: mysql:5.6
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: passroot
    - name: MYSQL_DATABASE
      value: serBooking
    ports:
     - containerPort: 3306
    
  - image: symfonypower/php7-symfony:1.0.0
    ports:
     - containerPort: 9000
    name: sowboy-api-code
    volumeMounts:
     - mountPath: "/var/www"
       name: api-pv-storage
  - image: symfonypower/apache:1.0.0
    ports:
     - containerPort: 80
       name: "http-server"
    name: sowboy-booking-api
    volumeMounts:
     - mountPath: "/var/www/html"
       name: api-pv-storage
  
      
  
   
