version: '3.1'

services:

  app:
    container_name: sowboy-apps
    image: symfonypower/php7-symfony:1.0.0
    ports: 
      - 9000:9000
    links:
      - db
  apache:
    container_name: sowboy-apache
    image: symfonypower/apache:1.0.0
    links:
      - db
    ports:
      - 80:80
    labels: 
      kompose.service.type: nodeport
    privileged: true

  db:
    container_name: sowboy-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passroot
      MYSQL_DATABASE: serBooking

