version: '3.1'

services:

  app:
    container_name: sowboy-apps
    image: symfonypower/php7-symfony:1.0.0
    ports: 
      - 9000:9000
    links:
      - db
    volumes:
      - ./:/var/www

  apache:
    container_name: sowboy-apache
    image: symfonypower/apache:1.0.0
    volumes:
      - ./:/var/www/html
    links:
      - db
    ports:
      - 80:80
    labels: 
      kompose.service.type: nodeport
    privileged: true

  db:
    container_name: sowboy-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dump-sql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: passroot
      MYSQL_DATABASE: serBooking

